package com.socks.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STAFF_TABLE".
 */
public class StaffTable {

    private Long id;
    private String staffName;
    private String staffNum;
    private Integer staffAge;
    private String motto;
    private Long insertTime;

    public StaffTable() {
    }

    public StaffTable(Long id) {
        this.id = id;
    }

    public StaffTable(Long id, String staffName, String staffNum, Integer staffAge, String motto, Long insertTime) {
        this.id = id;
        this.staffName = staffName;
        this.staffNum = staffNum;
        this.staffAge = staffAge;
        this.motto = motto;
        this.insertTime = insertTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStaffName() {
        return staffName;
    }

    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    public String getStaffNum() {
        return staffNum;
    }

    public void setStaffNum(String staffNum) {
        this.staffNum = staffNum;
    }

    public Integer getStaffAge() {
        return staffAge;
    }

    public void setStaffAge(Integer staffAge) {
        this.staffAge = staffAge;
    }

    public String getMotto() {
        return motto;
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }

    public Long getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(Long insertTime) {
        this.insertTime = insertTime;
    }

}
